from openai import OpenAI
from dotenv import load_dotenv
from os import getenv


# Load environment variables from the .env file
load_dotenv()


# Create the API client
# It uses the NVIDIA API endpoint and NVIDIA API key
client = OpenAI(
    api_key=getenv("NVIDIA_API_KEY"),
    base_url="https://integrate.api.nvidia.com/v1"
)


# Function: Get English text from the user
# Work: Takes input from the user and returns the text
def get_input():
    text = input("Enter English text: ")
    return text


# Function: Create the prompt for the AI model
# Work: Takes user's English text and creates a translation instruction
def create_prompt(text):
    prompt = f"""
Translate the following English text into Hindi.

English:
{text}

Return only the Hindi translation.
"""
    return prompt


# Function: Send the prompt to the LLM
# Work: Sends the prompt to GPT-OSS-20B and returns the AI response
def call_llm(client, prompt):
    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    # Extract only the actual text generated by the AI
    return response.choices[0].message.content


# Function: Main program controller
# Work: Calls all functions in the correct order
def main():

    # Step 1: Get input from user
    text = get_input()

    # Step 2: Create prompt using the user's text
    prompt = create_prompt(text)

    # Step 3: Send prompt to AI and get translation
    translation = call_llm(client, prompt)

    # Check whether API returned a result
    if translation is not None:
        print("\nHindi:", translation)
    else:
        print("\nTranslation failed.")




# This checks whether this file is being run directly
# If yes, start the main() function
if __name__ == "__main__":
    main()